#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dazgveva.Reportebi
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SocialuriDazgveva")]
	public partial class UsersDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public UsersDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SocialuriDazgvevaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public UsersDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UsersDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UsersDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UsersDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User
	{
		
		private string _RAI_NAME;
		
		private string _USER_NAME;
		
		private string _USER_FULL_NAME;
		
		private string _PSWHASH;
		
		private string _REGION_ID;
		
		private System.Nullable<int> _REGION_ID_Orig;
		
		private string _ROLE_NAME;
		
		public User()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RAI_NAME", DbType="NVarChar(1000)")]
		public string RAI_NAME
		{
			get
			{
				return this._RAI_NAME;
			}
			set
			{
				if ((this._RAI_NAME != value))
				{
					this._RAI_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_NAME", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string USER_NAME
		{
			get
			{
				return this._USER_NAME;
			}
			set
			{
				if ((this._USER_NAME != value))
				{
					this._USER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_FULL_NAME", DbType="NVarChar(1000)")]
		public string USER_FULL_NAME
		{
			get
			{
				return this._USER_FULL_NAME;
			}
			set
			{
				if ((this._USER_FULL_NAME != value))
				{
					this._USER_FULL_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PSWHASH", DbType="Char(32) NOT NULL", CanBeNull=false)]
		public string PSWHASH
		{
			get
			{
				return this._PSWHASH;
			}
			set
			{
				if ((this._PSWHASH != value))
				{
					this._PSWHASH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REGION_ID", DbType="NVarChar(4)")]
		public string REGION_ID
		{
			get
			{
				return this._REGION_ID;
			}
			set
			{
				if ((this._REGION_ID != value))
				{
					this._REGION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REGION_ID_Orig", DbType="Int")]
		public System.Nullable<int> REGION_ID_Orig
		{
			get
			{
				return this._REGION_ID_Orig;
			}
			set
			{
				if ((this._REGION_ID_Orig != value))
				{
					this._REGION_ID_Orig = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLE_NAME", DbType="NVarChar(1000)")]
		public string ROLE_NAME
		{
			get
			{
				return this._ROLE_NAME;
			}
			set
			{
				if ((this._ROLE_NAME != value))
				{
					this._ROLE_NAME = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
